name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 14
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 14
    - name: versions
      run: java -version && mvn -v
    - name: Test
      run: mvn -B clean compile test
